name: Publish to npm

on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Name of the tag to create'
        required: true

jobs:
  tag-packages:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Install pnpm
        run: npm install -g pnpm
      - name: Use Node.js 22.x
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: 'pnpm'
      - run: pnpm install
      - name: Set version in package.json
        run: |
          pnpm release packages/@baldeweg ${{ inputs.tag_name }}
      - name: Commit Version Changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update version"
          file_pattern: packages/@baldeweg/**/*
  tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Git user
        run: |
          git config --global user.email "a@baldeweg.org"
          git config --global user.name "André Baldeweg"
      - name: Tag the commit
        run: git tag -a ${{ inputs.tag_name }} -m "Version ${{ inputs.tag_name }}"
      - name: Push the tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: git push origin ${{ inputs.tag_name }}
  release-docu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install pnpm
        run: npm install -g pnpm
      - name: Use Node.js 22.x
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: 'pnpm'
          registry-url: 'https://registry.npmjs.org'
      - run: pnpm install
      - name: Publish @baldeweg/docu to NPM
        run: pnpm -F @baldeweg/docu publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
  release-eslint-config:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install pnpm
        run: npm install -g pnpm
      - name: Use Node.js 22.x
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: 'pnpm'
          registry-url: 'https://registry.npmjs.org'
      - run: pnpm install
      - name: Publish @baldeweg/eslint-config to NPM
        run: pnpm -F @baldeweg/eslint-config publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
  release-ui:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install pnpm
        run: npm install -g pnpm
      - name: Use Node.js 22.x
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: 'pnpm'
          registry-url: 'https://registry.npmjs.org'
      - run: pnpm install
      - run: pnpm -F @baldeweg/ui build
      - name: Publish @baldeweg/ui to NPM
        run: pnpm -F @baldeweg/ui publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
