name: Publish to npm

on:
  push:
    tags:
      - 'v*'

jobs:
  release-docu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 22.x
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: 'pnpm'
          registry-url: 'https://registry.npmjs.org'
      - run: pnpm install
      - name: Publish @baldeweg/docu to NPM
        run: pnpm -F @baldeweg/docu publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
  release-eslint-config:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 22.x
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: 'pnpm'
          registry-url: 'https://registry.npmjs.org'
      - run: pnpm install
      - name: Publish @baldeweg/eslint-config to NPM
        run: pnpm -F @baldeweg/eslint-config publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
  release-ui:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 22.x
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: 'pnpm'
          registry-url: 'https://registry.npmjs.org'
      - run: pnpm install
      - run: pnpm -F @baldeweg/ui build
      - name: Publish @baldeweg/ui to NPM
        run: pnpm -F @baldeweg/ui publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
