name: Unit-Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-ui:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 22.x
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: 'pnpm'
      - run: pnpm install
      - run: pnpm -F @baldeweg/ui build
      - run: pnpm -F @baldeweg/ui test:unit:ci
