name: Unit-Tests

on:
  push:
    branches:
      - main
    tags:
      - 'v*'

  pull_request:
    branches:
      - main

jobs:
  release:
    # needs: [test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 22.x
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: 'yarn'
          registry-url: 'https://registry.npmjs.org'
      - run: yarn install
      - run: yarn workspace @baldeweg/ui build
      - name: Publish to NPM
        run: yarn workspace @baldeweg/ui publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
  docu:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 22.x
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: 'yarn'
      - run: yarn install
      - name: Generate Documentation
        run: yarn workspace @baldeweg/ui docu
      - name: Commit Documentation Changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "docs: update documentation"
          file_pattern: packages/@baldeweg/ui/docu/*
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 22.x
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: 'yarn'
      - run: yarn install
      - run: yarn workspace @baldeweg/ui build
      - run: yarn workspace @baldeweg/ui test:unit:ci
